[plugins]
# docker = "https://github.com/kiliantyler/asdf-dockercli.git"
# qemu = "https://github.com/kiliantyler/asdf-qemu.git"
# docker-buildx = "https://github.com/kiliantyler/asdf-dockerbuildx.git"

[tools]
goss = "0.4.8"
yq = "4.44.3"
yamlfmt = "0.13.0"
cue = "0.10.0"
task = "3.38.0"
# qemu = "latest"
lima = "latest"
colima = "latest"
# docker = "latest"
# docker-buildx = "latest"
