# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  CHANNEL: '{{ default "stable" .CHANNEL }}'
  LABELS_CONFIG_FILE: '{{ .ROOT_DIR }}/.github/labels.yaml'
  LABELER_FILE: '{{ .ROOT_DIR }}/.github/labeler.yaml'

includes:
  app: './.taskfiles/App'

tasks:
  default:
    silent: true
    cmds:
    - task -l
