#!/usr/bin/env zsh

# +log:message

# **This should not be called directly, it should be called from the +zgo::log:<log-level> functions**

# Input:
#   $@ -- The message to be printed
#
# Output:
#   The message is printed to the terminal

#function +zgo::log:message{
  builtin emulate -LR zsh -o extendedglob ${=${options[xtrace]:#off}:+-o xtrace}
  local opt msg
  [[ $1 = -* ]] && { local opt=$1; shift; }
  msg=${${(j: :)${@:#--}}//\%/%%}
  builtin print -Pr ${opt:#--} -- $msg >> /dev/tty

  # Needed to properly end a message with {nl}.
  if [[ -n ${opt:#*n*} || -z $opt ]]; then
    print -n $'\015'
  fi

#}
