#!/usr/bin/env zsh

local -A aliasMap

aliasMap=(
  [gc]="gitclone"
  [gitc]="gitclone"
)

if [[ -n $1 ]]; then
  REPLY=${aliasMap[$1]}
else
  echo "Usage: util:getalias <alias>"
  REPLY=""
  return 1
fi

return 0
