# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Scheduled Release

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appsToBuild:
        description: App(s) to build, comma separated, or 'all' | 'base' | 'apps'
        required: false
        type: string
        default: all
      force:
        description: Force rebuild
        type: boolean
        default: false
        required: true
  schedule:
  - cron: "0 * * * *" # Every hour

jobs:
  simple-checks:
    name: Simple Checks
    uses: shamubernetes/containers/.github/workflows/simple-checks.yaml@b7d25daf0f118dfdd8559bb9df26ca5238755c1b # main

  build-images:
    name: Build Images
    needs: simple-checks
    uses: shamubernetes/containers/.github/workflows/build-images.yaml@b7d25daf0f118dfdd8559bb9df26ca5238755c1b # main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      appsToBuild: ${{ inputs.appsToBuild }}
      force: ${{ inputs.force == true }}
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs: build-images
    uses: ./.github/workflows/render-readmes.yaml
    secrets: inherit
