# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release on Merge

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  push:
    branches: ["main"]
    paths:
    - "apps/**"
    - ".github/scripts/templates/**"
    - ".github/scripts/render-readme.py"
    - "!apps/**/README.md"

jobs:
  simple-checks:
    uses: shamubernetes/containers/.github/workflows/simple-checks.yaml@main

  get-changed-images:
    needs: ["simple-checks"]
    uses: shamubernetes/containers/.github/workflows/get-changed-images.yaml@main

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: shamubernetes/containers/.github/workflows/build-images.yaml@main
    secrets: inherit
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs: build-images
    if: ${{ always() && needs.build-images.result != 'failure' }}
    uses: ./.github/workflows/render-readmes.yaml
    secrets: inherit
